# Generated by Django 5.0.3 on 2024-03-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=10)),
                ('smail', models.EmailField(max_length=254)),
            ],
        ),
    ]
